### ISSUE TITLE
When having these error,it won't let me get access token until I kill the app and open again.

### ISSUE THREAD

**Issue by htarwara6245** [telenordigital/connect-ios-sdk#28]
I am experiencing these error at my log.Also on many devices which use this Telenor Connect Login Service.

```
error=Optional("The operation couldn’t be completed. (AGAuthzErrorDomain error 0.)")
error=Optional("The operation couldn’t be completed. (TDConnectIosSdk.OAuth2Error error 2.)")
```

OAuth2Error error (xxxx) codes might be different base on client situation.

State : 1 => If I open connect login page without doing anything (Idle) and login by filling appropriate form.That error appear.So,If those errors appear,I can't get access Token until I close the app,open and login again.

State : 2 => If I wrongly type my password 3 times and at the 4th time,I correctly type and went login,that error also happen too.It can also solved when I close the app and remove from multitasking.And open the app again,it worked.

I really don't know the reason why it didn't let me pass the access token when those error appear until the client close the app,remove the app from multitasking,open again and do the appropriate login steps.

Any Help?

**Comment by jorunfa** [comment]
Hi! I'll look at into it as soon as I can. I'm not sure I can make that happen the next couple of days, but I will as soon as possible.

**Comment by jorunfa** [comment]
The error sounds familiar to a bug fixed in [version 0.7.2](https://github.com/telenordigital/connect-ios-sdk/releases). Which version are you using?

**Comment by htarwara6245** [comment]
Yeah 0.7.1.I will check it at 0.7.2.

**Comment by htarwara6245** [comment]
error=Optional("The operation couldn’t be completed. (TDConnectIosSdk.OAuth2Error error 2.)") is still happening on Version : '0.8.0'. Can you please take a look?

**Comment by jorunfa** [comment]
I believe `OAuth2Error error 2` is the `UnequalStateParameter` error. See the `state` parameter in the docs: http://docs.telenordigital.com/apis/connect/id/authentication.html#authorization-server-user-authorization .

It's possible it can be triggered by starting a new sign in flow before a previous one has completed. Is that a possibility?

If not, could you send a video of what is happening?

**Comment by htarwara6245** [comment]
Actually I want to but, It's rare. But,I can provide you the state.

1. I was testing on iOS 10.1.1, iPhone 6.
2. The SDK did correctly until it close SFSafariViewController means the authorization code didn't return and instead return this error log.
3. Then I killed the app from memory and open it again and login the same process, it passed.

**Comment by jorunfa** [comment]
Try setting a breakpoint at line 99 and 108 in `OAuth2Module`, to inspect the `state` and `stateFromRedirectUrl` variables. 

Line 99 should be called when you click the button and start a sign in. Line 108 is called when the callback to the application is called, from the redirect url. These two states must match, or else `UnequalStateParameter` error will be thrown.

![image](https://cloud.githubusercontent.com/assets/1413275/21448285/2e948fb6-c8e1-11e6-8cfb-d94b18b139b0.png)

**Comment by htarwara6245** [comment]
Ok I will checked. In a mean while I will close this issue for now. But be right back when I got this again.
